# Generated by Django 6.0.3 on 2026-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tech_role',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'Devops'), ('tester', 'Tester'), ('fullstack', 'Fullstack')], max_length=20, null=True),
        ),
    ]
